server:
  port : 8081

spring :
  datasource:
    url: jdbc:postgresql://ec2-44-195-191-252.compute-1.amazonaws.com:5432/dam1l0qn07hmqu
    driver-class-name: org.postgresql.Driver
    username: wyryoeavqqbyxv
    password: 9bc33d757089582d582b53cbcfe8faf86d23a08b108349cad1cdedcd87ac6184

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql : true
            show_sql : true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#jwt:
#  header : Authorization
#  secret : amh3b24td2lsbC1iZS10aGUtYmVzdC1wcm9ncmFtbWVyLWluLXRoZS13b3JsZC13YXRjaC1teS1qb3VybmV5LXRoaXMtaXMtYWJvdXQtbXktZmlyc3RTZWNyZXRLZXkK # 특정 문자열을 Base64로 인코딩한 값
#  token-validity-in-seconds : 80400 # token expired time

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400